# Generated by Django 4.2 on 2023-06-08 23:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='alzhimarTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gender', models.IntegerField()),
                ('Age', models.FloatField()),
                ('EDUC', models.FloatField()),
                ('SES', models.FloatField()),
                ('MMSE', models.FloatField()),
                ('eTIV', models.FloatField()),
                ('nWBV', models.FloatField()),
                ('ASF', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('result', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
