# Generated by Django 4.2 on 2023-06-08 23:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('glucouse', models.FloatField()),
                ('insuline', models.FloatField()),
                ('homa', models.FloatField()),
                ('leptin', models.FloatField()),
                ('adiponcetin', models.FloatField()),
                ('resistiin', models.FloatField()),
                ('mcp', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('result', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
