# Generated by Django 4.2 on 2023-06-08 23:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='heartTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Age', models.FloatField()),
                ('Sex', models.IntegerField()),
                ('ChestPainType', models.FloatField()),
                ('Cholesterol', models.FloatField()),
                ('FastingBS', models.FloatField()),
                ('MaxHR', models.FloatField()),
                ('ExerciseAngina', models.FloatField()),
                ('Oldpeak', models.FloatField()),
                ('ST_Slope', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('result', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
